---
title: "Les cotisations sociales"
---

## Présentation générale

*[À rédiger.]*


## Les cotisations sociales

*[À rédiger.]*


### Cotisations de Sécurité Sociale

*[À rédiger.]*


### Régime de l'assurance chômage

*[À rédiger.]*


### Régimes complémentaires de retraite

*[À rédiger.]*


### Secteur public

*[À rédiger.]*


## Taxes et participations assises sur les salaires

*[À rédiger.]*


### Taxe sur les salaires

*[À rédiger.]*


### Effort à la construction

*[À rédiger.]*


### Fonds national d'aide au logement (FNAL)

*[À rédiger.]*


### Cotisations accidents

*[À rédiger.]*


### Participation des employeurs à la formation professionnelle continue

*[À rédiger.]*


### Taxe d'apprentissage

*[À rédiger.]*


### Versement transport (VT)

*[À rédiger.]*


### Taxe spéciale sur les contributions patronales de prévoyance

*[À rédiger.]*


## Les réductions générales de cotisations patronales

*[À rédiger.]*


### Réduction de cotisations Allocation familiales

*[À rédiger.]*


#### De juillet 1993 à juillet 1994

A compter du 01/07/1993 : exonération totale de la cotisation
d'allocations familiales pour les salaires mensuels inférieurs à 1,1
Smic (169h) et réduction de moitié (2,7% au lieu de 5,4%) pour les
salaires compris entre 1,1 et 1,2 Smic.

[Référence:]{.smallcaps} Loi 93-353 du 27/07/1993.\
[Source:]{.smallcaps} BSP no 22 de juillet 1993

#### De juillet 1994 à décembre 1994

Cas général:

:   Entre 1 et 1,1 Smic : exonération totale d'allocations familiales (=
    5,4%)\
    Entre 1,1 et 1,3 Smic : exonération de 2,7% d'allocations familiales

Entreprises nouvelles

:   Entre 1 et 1,5 Smic : exonération totale d'allocations familiales (=
    5,4%)\
    Entre 1,5 et 1,6 Smic : exonération de 2,7% d'allocations
    familiales\

[Référence:]{.smallcaps} Loi quinquennale sur l'emploi et la formation
professionnelle 93-1313 du 20/12/1993 (JO 21/12/1993)

#### Janvier 1995 - août 1995

BSP, entrée \"SECURITE SOCIALE\"

Cas général : Entre 1 et 1,2 Smic : exonération totale d'allocations
familiales (= 5,4%) Entre 1,2 et 1,3 Smic : exonération de 2,7%
d'allocations familiales

Entreprises nouvelles Entre 1 et 1,5 Smic : exonération totale
d'allocations familiales (= 5,4%) Entre 1,5 et 1,6 Smic : exonération de
2,7% d'allocations familiales

[Référence:]{.smallcaps} Loi quinquennale 93-1313 du 20/12/93 (JO
21/12/93)

#### Septembre 1995 - septembre 1996

BSP, entrée \"SECURITE SOCIALE\"

Cas général : Entre 1 et 1,2 Smic : exonération totale d'allocations
familiales (= 5,4%) Entre 1,2 et 1,3 Smic : exonération de 2,7%
d'allocations familiales

Entreprises nouvelles Entre 1 et 1,5 Smic : exonération totale
d'allocations familiales (= 5,4%) Entre 1,5 et 1,6 Smic : exonération de
2,7% d'allocations familiales

[Référence:]{.smallcaps} Loi quinquennale 93-1313 du 20/12/93 (JO
21/12/93)

### Réduction dégressive sur les bas salaires, dite ristourne Juppé

*[À rédiger.]*


#### Septembre 1995 - septembre 1996

BSP, entrée \"EMPLOI (AIDE A L')\" (01/96, 04/96, 7/96)

Réduction dégressive des cotisations à la charge des employeurs au titre
des assurances sociales, des accidents du travail et des allocations
familiales, sur les salaires mensuels compris entre 1 et 1,2 Smic,
versés à compter du 1er septembre 1995. Plafond de rémunération : 7 500
F/mois (01/96), 7 650 F/mois (04/96), 7 688 F/mois (07/96)

$$RED = (PLAFOND - Salaire~brut) \times 0,64$$

Réduction maximale : 800 F (01/96), 816F (04/96), 820 F (07/96) pour un
salarié rémunéré au Smic à temps plein (36,98 x 169) x 0,128 (01/96),
(37,72 x 169) x 0,128 (01/96), (37,91 x 169) x 0,128 (07/96) Spécificité
à partir de juillet 1996 : +10% pour les entreprises relevant des
caisses de congés payés (d'où réduction maximum = 902 F) Modalités
spécifiques en cas d'horaires incomplets, de suspension du contrat et
pour certaines catégories particulières de salariés Bulletin de paie :
indiquer le montant de la réduction Calcul direct par l'employeur et
déduction des versements à l'URSSAF. Ligne supplémentaire sur le BRC.

[Référence:]{.smallcaps} Loi 95-882 du 04/08/95 (JO 05/08/95). Décrets
95-942 et 943 du 25/08/95 (JO 26/98/95)

### Octobre 1996 - Décembre 1997

BSP, entrée \"EMPLOI (AIDE A L')\"

Réduction unique dégressive : Entre 1 et 1,33 Smic sur les salaires
versés depuis le 01/10/96. Plafond de rémunération : 8521,03 F/mois
(10/96) Calcul de la réduction :

  ----------------------------------------- -----------------------------------------
  Salaire inférieur au Smic mensuel         $R = \text{salaire} \times 0,182$
  Salaire compris entre Smic et 1,33 Smic   $R = (1,33.Smic - salaire) \times 0,55$
  ----------------------------------------- -----------------------------------------

Réductions majorées de 10% pour les entreprises relevant d'une caisse de
congés payés Réduction maximale : 1 166 F / 1283F si congés payés
(10/96) En 1996, réduction maximale de 1 166 F pour un salarié rémunéré
au Smic à temps plein (1 283 F si entreprise relève d'une caisse de
congés payés). Non cumulable avec autre exonération totale ou partielle
de cotisations patronales ou avec application de taux ou montant de
cotisations spécifiques sauf avec abattement de cotisations à temps
partiel et avec allègement réduction et amènagement du temps de travail.

[Référence:]{.smallcaps} Loi de finances pour 1996 95-1236 du 30/12/95
(JO 31/12/95). Décret 96-835 du 20/09/96 (JO 22/09/96)

BSP, entrée \" SECURITE SOCIALE \"

Exonération de la cotisation d'AF totale pour les entreprises situées en
zone de revitalisation rurale ou pour les entreprises nouvelles
exonérées d'impôt (à compter du 01/10/96, les autres entreprises
appliquent la réduction unique dégressive) : - réduction unique
dégressive en dessous de 1,2 Smic (identique à la réduction générale) -
totale entre 1,2 de 1,5 Smic - de moitié (soit 2,7% au lieu de 5,4%)
entre 1,5 et 1,6 Smic

Source : Loi de finances pour 1998 (JO 31/12/97)

### Janvier 1998 à Décembre 1999

*[À rédiger.]*


#### Réduction unique dégressive

BSP, entrée \"EMPLOI (AIDE A L')\"

Entre 1 et 1,3 Smic sur les salaires versés depuis le 01/01/98. Plafond
de rémunération : 8 946,18 F/mois (01/00) Calcul de la réduction : -
Salaire inférieur au Smic mensuel : R=salaire x 0,182 - Salaire compris
entre Smic et 1,3 Smic : R= (1,3 x Smic - salaire) x 0,607 Réductions
majorées de 10% pour les entreprises relevant d'une caisse de congés
payés. Proratisation en cas de travail à temps partiel Réduction
maximale : 1 252,45 F Non cumulable avec autre exonération totale ou
partielle de cotisations patronales ou avec application de taux ou
montant de cotisations spécifiques sauf avec abattement de cotisations à
temps partiel et avec allègement réduction et amènagement du temps de
travail.

Source : Loi de finances pour 1998 97-1269 du 30/12/1997 (JO 31/12/97).
Décret 97-1330 du 31/12/97 (JO 03/01/98)

BSP, entrée \" SECURITE SOCIALE \"

Exonération de la cotisation d'AF totale pour les entreprises situées en
zone de revitalisation rurale ou pour les entreprises nouvelles
exonérées d'impôt - totale en-dessous de 1,5 Smic - de moitié (soit 2,7%
au lieu de 5,4%) entre 1,5 et 1,6 Smic

En 2000, ce système est maintenu pour les entreprises qui ne seront pas
passées au 35 heures

Dans le BSP N°51 du 31/10/00, aides au passage aux 35 heures sont
détaillées.

#### Allègement 35 heures, dit Aubry I

L'article 3 de la loi 98-461 du 13 juin 1998 d'orientation et
d'incitation relative à la réduction du temps de travail (dite loi Aubry
I) prévoit une aide forfaitaire, dégressive au cours du temps, d'autant
plus importante que les entreprises ont signé tôt un accord sur la
réduction du temps de travail et d'autant plus importante que la
réduction du temps de travail mise en place est importante.

Cela conduit à différents barèmes selon la date de l'accord
d'entreprise, le type d'accord et la durée depuis l'accord.

[Références:]{.smallcaps} Annexe des décrets 98-494 du 22/06/1998 et
2000-84 du 31/01/2000 Lefebvre Social 2003, no 9590.

### Janvier 2000 à juillet 2003

Mis en place par la loi 2000-37 du 19 janvier 2000.

#### Entreprises restées aux 39 heures

Maintien des exonérations Juppé précédentes.

#### Allègement 35 heures, dit Aubry II

Barème au 29 janvier 2000, avec un minimum de 4000 FRF (par an):

$$REDUCTION = \frac{1}{12} \times \Big[\frac{41,500~FRF \times 6881,68~FRF}{RMB} - 20,000~FRF\Big]$$

Cela implique une réduction maximale de 26% au niveau du Smic (soit
21,500 FRF annuel, le smic mensuel étant alors de 6881,68 FRF) qui
devient forfaitaire à 4000 FRF au niveau de 1,73 Smic.\
[Référence:]{.smallcaps} Décret 2000-73 du 28 janvier 2000 - art. 1 JORF
29 janvier 2000; Article D241-13 du Code de la sécurité sociale

Barème au 1janvier 2003:
$$REDUCTION = \frac{1}{12} \times \Big[\frac{6,720~\euro \times \text{SMIC~mensuel}}{RMB} - 3238,57~\euro\Big]$$

[Sources:]{.smallcaps} Lefebvre Social 2000, p. 95; Lefebvre Social
2003, p. 84

### Exonérations Fillon

Période 2003-2005: harmonisation des salaires minimum, harmonisation des
baisses de charges. Voir Bunel et al. (2009).

#### Dispositif au 1juillet 2003

$$REDUCTION = RMB \times \Big[\frac{0,26}{0,7}\Big]\times \Big[1,7 \times \frac{SMIC~horaire \times NBHRS}{RMB} - 1\Big]$$

Avec $0<REDUCTION <=0,26~RMB$

[Sources:]{.smallcaps} Décret 2003-487 du 11 juin 2003 portant
application du titre III de la loi 2003-47 du 17 janvier 2003 relative
aux salaires, au temps de travail et au développement de l'emploi et
modifiant le code de la sécurité sociale (modifié par décret 2005-88 du
4 février 2005).

Décret 2004-821 du 18 août 2004 portant application à certains régimes
spéciaux de sécurité sociale du titre III de la loi 2003-47 du 17
janvier 2003 relative aux salaires, au temps de travail et au
développement de l'emploi, modifié par le décret 2005-948 du 2 août
2005.

#### Dispositif au 1juillet 2005

$$REDUCTION = RMB \times \Big[\frac{0,26}{0,6}\Big]\times \Big[1,6 \times \frac{SMIC~horaire \times NBHRS}{RMB} - 1\Big]$$

Avec $RMB$ la rémunération mensuelle brute et $NBHRS$ le nombre d'heures
rémunérées.

#### Dispositif au 1juillet 2007

**Entreprises de plus de 20 salariés:**
$$REDUCTION = RMB \times \Big[\frac{0,26}{0,6}\Big]\times \Big[1,6 \times \frac{SMIC~horaire \times NBHRS}{RMB} - 1\Big]$$

Avec $RMB$ la rémunération mensuelle brute et $NBHRS$ le nombre d'heures
rémunérées.

**Entreprises de 1 à 19 salariés:**
$$REDUCTION = RMB \times \Big[\frac{0,281}{0,6}\Big]\times \Big[1,6 \times \frac{SMIC~horaire \times NBHRS}{RMB} - 1\Big]$$

Références: article 41-V de la loi 2006-1666 du 21 décembre 2006 de
finances pour 2007 et article 53-VII de la loi 2007-290 du 5 mars 2007
instituant le droit au logement opposable et portant diverses mesures en
faveur de la cohésion sociale.

#### Dispositif au 1octobre 2007

La rémunération mensuelle (hors heures supplémentaires et
complémentaires) se substitue à la référence au salaire horaire dans les
formules de calcul qui sont désormais ainsi établies :

**Entreprises de plus de 20 salariés:**
$$REDUCTION = RMB \times \Big[\frac{0,26}{0,6}\Big]\times \Big[1,6 \times \frac{SMIC~mensuel}{RMB} - 1\Big]$$

Avec $RMB$ la rémunération mensuelle brute.

**Entreprises de 1 à 19 salariés:**
$$REDUCTION = RMB \times \Big[\frac{0,281}{0,6}\Big]\times \Big[1,6 \times \frac{SMIC~mensuel}{RMB} - 1\Big]$$

Références: loi 2007-1223 du 21 août 2007 en faveur du travail, de
l'emploi et du pouvoir d'achat

#### Dispositif au 1janvier 2011

projet de loi de financement de la sécurité sociale pour 2011

**Entreprises de plus de 20 salariés:**
$$REDUCTION = RMB \times \Big[\frac{0,26}{0,6}\Big]\times \Big[1,6 \times \frac{SMIC~annuel}{RAB} - 1\Big]$$

Avec $RAB$ la rémunération annuelle brute.

**Entreprises de 1 à 19 salariés:**
$$REDUCTION = RMB \times \Big[\frac{0,281}{0,6}\Big]\times \Big[1,6 \times \frac{SMIC~annuel}{RAB} - 1\Big]$$
