---
title: "Les impôts sur le patrimoine"
---

## Les droits de mutation à titre gratuit 

Les mutations à titre gratuit recouvrent les transmissions sans
contrepartie pour cause de décès, c'est-à-dire les successions, et les
transmissions à titre gratuit entre vifs, c'est-à-dire les donations.

### Historique

L'imposition des mutations à titre gratuit est devenue générale et
systématique en France avec la loi des 5 et 19 décembre 1790 [@loi1790] qui
assujettit ces transmissions à un droit d'enregistrement. Cette loi a,
elle-même, été remplacée par celle du 22 frimaire an VII, qui prévoyait
des régimes fiscaux différents pour les successions et pour les
donations. Ils avaient toutefois pour trait commun de comporter
l'application, à la valeur brute de l'actif transmis, de taux
proportionnels variant non seulement, comme maintenant, en fonction des
liens de parenté existant entre le donateur et les bénéficiaires de la
mutation mais encore en raison du caractère mobilier ou immobilier des
biens en cause.

La loi du 25 février 1901 [@loi1901] a accentué la différence entre l'imposition
des donations et celle des successions d'une part en instituant pour
celles-ci un tarif progressif et, d'autre part, en autorisant, sous
certaines conditions, la déduction du passif héréditaire pour l'assiette
des droits de succession.

Mais la loi du 14 mars 1942 [@loi1942], rompant sur ce point avec la législation
antérieure, a, au contraire, tendu à unifier le régime fiscal des
mutations à titre gratuit en généralisant, dans toute la mesure du
possible, les règles applicables aux successions. À cet effet, le
législateur a pris trois sortes de mesures :

\- il a rendu applicables aux donations certaines règles d'assiette dont
la portée était précédemment limitée aux successions ;

\- il a étendu à toutes les mutations à titre gratuit les tarifs prévus
pour les mutations par décès (tarifs proprement dits, abattements sur
l'actif, réduction sur les droits), sous réserve de quelques
dispositions d'exception concernant des cas particuliers
(donations-partages, donations par contrat de mariage) ;

\- enfin, il a établi des règles nouvelles de liquidation tendant à
considérer les diverses donations consenties par une personne et la
transmission par décès de son patrimoine comme formant un tout pour
l'application de l'impôt.

Ces règles fondamentales n'ont pas été affectées par les interventions
législatives qui ont fréquemment eu lieu depuis 1942. Celles-ci ont,
dans un premier temps, tendu à nuancer et à alléger la charge de l'impôt
en créant de nombreux cas d'exonération et régimes spéciaux. Toutefois,
depuis 1974, une nouvelle orientation s'était développée tendant à
réduire la portée des exonérations existantes. Pour des motifs liés à la
conjoncture économique, de nouvelles exonérations et de nouveaux régimes
particuliers ont été créés ces dernières années.

D'autre part, diverses dispositions ont modifié les tarifs et barèmes et
actualisé le montant des abattements. En dernier lieu, la loi portant
diverses dispositions d'ordre économique et financier du 12 avril 1996
réforme la fiscalité des donations et des donations-partages, afin de
faciliter la transmission entre vifs des patrimoines par un allégement
des droits de mutation.

### Les droits de succession

*[À rédiger.]*


#### Mode de calcul

Avant d'être divisé en parts taxables entre les héritiers, l'actif
successoral, c'est-à-dire la valeur totale des biens de la succession,
fait l'objet d'une déduction des dettes à la charge personnelle du
défunt.

Depuis le 22 août 2007, le conjoint survivant et le partenaire lié par
un pacte civil de solidarité (PACS) sont exonérés de droits de
succession (CGI art. 796-0 bis). Le conjoint survivant bénéficiait
jusqu'à cette date de seuils d'imposition plus avantageux que ceux de la
succession en ligne directe, comme cela est toujours le cas pour les
donations entre vifs. Les successions entre partenaires de PACS, régies
de 2000 à 2007 par l'article 777 bis du Code général des impôts, étaient
soumises à un taux de 40% pour la fraction de la part nette taxable
n'excédant pas 15 000 € et à un taux de 50% pour le surplus.

La loi du 22 août 2007 [@loi2007-22aout] a également exonéré de droits de succcession les
frères et sœurs, célibataires, veufs, divorcés ou séparés, à la double
condition qu'ils soient âgés de plus de cinquante ans ou atteints d'une
infirmité, et qu'ils aient été constamment domiciliés avec le défunt
pendant les cinq années ayant précédé le décès (CGI art. 796-0 ter).
Auparavant ceux-ci bénéficiaient d'un simple abattement de
57 000 € depuis 2005.

Selon le degré de parenté existant entre le donateur et le bénéficiaire,
un abattement est appliqué sur les successions en 2012 sur la part nette
de chaque redevable et est fixé à :

-   159 325 € pour les personnes handicapées quel que soit leur degré de
    parenté (cet abattement est cumulable);

-   100 000 € pour les ascendants et les enfants ;

-   15 932 € pour les frères et sœurs, qui ne remplissent pas les
    conditions pour être éxonérés de droits de succession ;

-   7 967 € pour les neveux et nièces ;

-   1 594 € pour les autres héritiers.

Enfin, pour calculer les droits de succession, l'administration fiscale
établit un \"rappel fiscal\" : elle ajoute à la valeur des biens compris
dans la déclaration de succession, la valeur des biens qui ont fait
l'objet de donations antérieures à l'exception de celles qui remontent à
plus de 15 ans.

#### Taux applicables au 1er janvier 2013

Les droits de succession (qui sont aussi ceux de donation en ligne
directe) sont calculés en appliquant des taux marginaux par tranche à la
part nette taxable reçue par chaque bénéficiaire, diminuée le cas
échéant d'un abattement. On retrouve ces taux à l'article 777 du Code
général des impôts.

::: center
            **Barème d'imposition des droits de mutation en ligne directe**            
  ------------------------------------------------------------------------------------ ----------------------------------
                            Montant taxable après abattement                            Taux par tranche de part taxable
                                       $\leq$  €                                                       5%
     $\left[\nombre{8~072}~\textrm{\euro}~;~\nombre{12~109}~\textrm{\euro}\right]$                    10%
     $\left[\nombre{12~109}~\textrm{\euro}~;~\nombre{15~932}~\textrm{\euro}\right]$                   15%
    $\left[\nombre{15~932}~\textrm{\euro}~;~\nombre{552~324}~\textrm{\euro}\right]$                   20%
    $\left[\nombre{552~324}~\textrm{\euro}~;~\nombre{902~838}~\textrm{\euro}\right]$                  30%
   $\left[\nombre{902~838}~\textrm{\euro}~;~\nombre{1~805~677}~\textrm{\euro}\right]$                 40%
                              $\geq$ 1 805 677 [€]{.roman}                                            45%
:::

La loi prévoit également des barèmes d'imposition différents selon les
liens de parenté (frères et sœurs non exonérés, parents jusqu'au 4e
degré, parents au-delà du 4e degré et non-parents).

::: center
  **Barèmes d'imposition des donations en ligne collatérale et entre non-parents**   
  ---------------------------------------------------------------------------------- ----------------------------------
  Montant taxable après abattement                                                   Taux par tranche de part taxable
  *Entre frères et sœurs*                                                              
  N'excédant pas 24 430€                                                             35%
  Supérieur 24 430€                                                                  45%
  *Entre parents jusqu'au 4e degré inclusivement*                                    55%
  *Entre parents au-delà du 4e degré et non-parents*                                 60%
:::

#### Réformes récentes

De 1983 à 2008, les barèmes d'imposition des mutations en ligne directe
sont restés stables, accusant une légere augmentation lors de la
conversion en euros appliquée à partir de 2002. Ils ont ensuite été
actualisés régulièrement entre 2008 et 2013 dans la même proportion que
la limite supérieure de la première tranche du barème de l'impôt sur le
revenu et arrondis à l'euro le plus proche. Ces actualisations
correspondent à des augmentations n'excédant pas 3% des seuils
précédents.

Les taux du barème applicable aux successions (et aux donations en ligne
directe) ont été portés par la loi de finances rectificative pour 2011
du 29 juillet 2011 de 35 à 40 % pour l'avant-dernière tranche et de 40 à
45 % pour la dernière tranche.

La loi du 21 août 2007 [@loi2007-21aout] a non seulement exonéré les conjoints et
partenaires de PACS de tout droit de succession, mais a également
multiplié par deux le montant de l'abattement réservé aux enfants,
ascendants et aux personnes handicapées, qui passe de 76 000 à
150 000 €. Le montant de l'abattement pour les frères et sœurs non
exonérés passe de 5 000 €  à 15 000 €. Cette-même loi met en place un
nouvel abattement d'un montant de 7 500 €  pour les neveux et nièces.
Ces abattements seront ensuite actualisés au 1er janvier de chaque année
dans la même proportion que la limite supérieure de la première tranche
du barème de l'impôt sur le revenu et arrondis à l'euro le plus proche.
De même, l'abattement opéré sur les parts successorales des autres
héritiers, à défaut d'autre abattement, a été progressivement revalorisé
passant ainsi de 1 500 € en 2002 à 1 594 € en 2013.

### Les droits de donation

*[À rédiger.]*


#### Mode de calcul

En matière de donation, les dettes qui ont été contractées par le
donateur pour l'acquisition ou dans l'intérêt des biens transmis et qui
sont mises à la charge du donataire dans l'acte de donation sont
déductibles de l'assiette des droits de mutation à titre gratuit.

Pour le calcul des droits, les donations sont soumises aux mêmes
abattements que les successions en faveur des personnes handicapées,
enfants, ascendants et neveux et nièces. Les conjoints et partenaires de
PACS bénéficient d'un abattement de 80 724 €puisque les exonérations de
droits ne s'appliquent pas aux donations. D'autres abattements sont
prévus pour les donations aux petits-enfants (31 865 €) et
arrière-petits-enfants (5 310 €).

Les dons familiaux de sommes d'argent sont exonérés de droits de
mutation à titre gratuit dans la limite de 31 865 €, tous les quinze
ans, à la condition que le donateur ait moins de 80 ans et que le
donataire soit majeur. Cette exonération se cumule avec les abattements
dont bénéficient par ailleurs les donataires. Enfin ce type de donation
n'est pas pris en compte lors du calcul de la part successorale (art.
784 du CGI).

#### Taux applicables au 31 décembre 2012

Les barèmes applicables aux donations en ligne directe sont ceux des
successions en ligne directe. Il en est de même pour les barêmes
d'imposition des donations entre collatéraux et non-parents. Quant aux
conjoints et partenaires liés par un PACS, ils bénéficient d'un barème
plus avantageux aux seuils de tranches d'imposition plus bas.

::: center
       **Barème d'imposition des donations entre époux et partenaires d'un PACS**      
  ------------------------------------------------------------------------------------ ----------------------------------
                            Montant taxable après abattement                            Taux par tranche de part taxable
                                        $\leq$ €                                                       5%
     $\left[\nombre{8~072}~\textrm{\euro}~;~\nombre{15~932}~\textrm{\euro}\right]$                    10%
     $\left[\nombre{15~932}~\textrm{\euro}~;~\nombre{31~865}~\textrm{\euro}\right]$                   15%
    $\left[\nombre{31~865}~\textrm{\euro}~;~\nombre{552~324}~\textrm{\euro}\right]$                   20%
    $\left[\nombre{552~324}~\textrm{\euro}~;~\nombre{902~838}~\textrm{\euro}\right]$                  30%
   $\left[\nombre{902~838}~\textrm{\euro}~;~\nombre{1~805~677}~\textrm{\euro}\right]$                 40%
                              $\geq$ 1 805 677 [€]{.roman}                                            45%
:::

#### Réformes récentes

De 1983 à 2007, les abattement portant sur les donations entre
conjoints, puis entre partenaires de Pacs, suivent la même évolution que
les abattements sur les successions. De 2000 à 2007, la loi maintient la
différence de traitement des conjoints et des partenaires de PACS en
stabilisant le montant de leurs abattements respectivement à 76 000 €et
57 000 €. La réforme de 2007 porte l'abattement pour les partenaires de
PACS au niveau de celui des conjoints. Cet abattement sera ensuite
régulièrement actualisé pour atteindre 80 724 €en 2013. C'est également
la loi de 2007 qui institue l'exonération des droits de mutation entre
vifs pour les dons de sommes d'argent entre parents. Cette exonération
n'est d'abord que conditionnée à l'âge du bénéficiaire (nécessairement
majeur) et du donataire, ce dernier ne pouvant être âgé de plus de 65
ans selon la loi de 2007. Cette limite d'âge passe à 80 ans en 2010 sauf
en ce qui concerne les donations aux enfants et neveux et nièces. C'est
finalement la réforme de juillet 2011 qui généralise la limite d'âge de
80 ans pour le donateur, mais qui instaure aussi une contrainte
supplémentaire : l'exonération n'est désormais plus possible que tous
les dix ans. Depuis août 2012, ce délai est passé à quinze ans.

## L'impôt de solidarité sur la fortune (ISF)

*[À rédiger.]*


### Changements pris en compte dans le simulateur entre 1997 et 2010

majoration de 10% de l'ISF entre 1995 et 1998 :

:    \
    Cette majoration est appliquée sur l'impôt dû (après application des
    réductions et du plafonnement). Cette majoration a ensuite été
    intégrée au barème de l'ISF.

abattement sur la résidence principale :

:    \
    Créé en 1999 pour une valeur de 20%, passage de 20% à 30% à partir
    de l'année 2008 (loi TEPA)

changement de taux et de seuils :

:    \
    Voir le fichier `Barèmes IPP - paramètres_ISF`

### Plafonnement à 85%

Il existe un plafonnement des impôts à 85% des revenus. Les impôts pris
en compte ici sont la somme de l'ISF, de l'impôt sur le revenu ainsi que
les prélèvements sociaux et la CSG-CRDS. Depuis 1996, un plafonnement du
plafonnement a été mis en place. La réduction d'impôt au titre du
plafonnement ne peut excéder au maximum :

-   la moitié de l'impôt dû

-   ou si ce montant est plus important, l'impôt correspondant à un
    patrimoine taxable égal à la limite supérieure de la 2tranche du
    barème (patrimoine taxable égal à 2 450 000 € en 2011 pour un ISF dû
    de 11 000 €).

Cela signifie que les contribuables dont le patrimoine est inférieur à
la limite supérieure de la 2tranche du barème bénéficient intégralement
du plafonnement. Pour les contribuables dont le patrimoine taxable est
compris en 2008 entre 2 450 000 € et 3 620 000 €, le plafonnement est
limité à 11 000 €. Enfin, pour les contribuables dont le patrimoine est
supérieur à 3 620 000 €, le plafonnement est limité à la moitié de l'ISF
dû.

Pour l'année 2012, comme la méthode de calcul de l'ISF a été
radicalement modifiée, le plafonnement est supprimé.

### Dernières lois de finances rectificatives

Pour 2011 :

:   les patrimoines imposables inférieurs à 1 300 000 €  sont exonérés
    d'ISF (Loi n° 2011-900 du 29 juillet 2011 [@loi2011-900] de finances rectificative
    pour 2011). Les patrimoines supérieurs à 1 300 000 €  sont imposés à
    partir de 800 000 €.\

Pour 2012 :

:   la loi de finances rectificatives de juillet 2011 avait prévu que
    l'ISF 2012 ne comprendrait plus que deux tranches, l'imposition se
    faisant dès le premier euro. Par ailleurs, une décote aurait dû être
    appliquée sur le montant d'impôt dû pour les patrimoines taxables
    situés aux alentours des deux seuils (1 300 000 € et 3 000 000€.\
    Mais le changement de majorité présidentielle a conduit, pour l'ISF
    2012, à un retour de fait au barème de 2011. En effet, la loi n°
    2012-958 du 16 août 2012 de finances rectificative pour 2012
    instaure une contribution exceptionnelle aux personnes redevables de
    l'impôt de solidarité sur la fortune pour 2012. Cette contribution
    est liquidée selon le tarif de l'ISF 2011 et remplace de fait la
    nouvelle formule de l'ISF pour 2012, dont le montant est imputable
    sur la contribution.\

Pour 2013 :

:   un nouveau barème est insitué qui supprime la dernière tranche de
    l'ISF. Pour les redevables dont le patrimoine a une valeur nette
    taxable comprise entre 1 300 000 €  et 1 400 000 € , le montant de
    l'impôt calculé bénéficie d'une décote égale à 17 500 €  - 1,25 % P,
    où P est la valeur nette taxable du patrimoine.

::: center
  -------------------------------------------------------------------------------------- ------- -----------------------------------
                        **Barème d'imposition de l'ISF pour 2012**                               
                                     *(non appliqué)*                                            
                                         Tranches                                         Taux              Décote (en €)
                                         $\leq$ €                                          0%                    \_
   $\left[\nombre{1~300~000}~\textrm{\euro}~;~\nombre{1~400~000}~\textrm{\euro}\right]$   0,25%    $\nombre{24~500}-(7*0,25\%*P)$
   $\left[\nombre{1~400~000}~\textrm{\euro}~;~\nombre{3~000~000}~\textrm{\euro}\right]$   0,25%                  \_
   $\left[\nombre{3~000~000}~\textrm{\euro}~;~\nombre{3~200~000}~\textrm{\euro}\right]$   0,5%    $\nombre{120~000}-(7,5*0,25\%*P)$
                               $\geq$ 3 200 000 [€]{.roman}                               0,5%                   \_
                     *Avec P, la valeur taxable nette du patrimoine*                             
  -------------------------------------------------------------------------------------- ------- -----------------------------------
:::

::: center
                        **Barème d'imposition de l'ISF pour 2013**                        
  --------------------------------------------------------------------------------------- ------------------
                            Fraction du patrimoine net taxable                             Tarif applicable
                                         $\leq$ €                                                 0%
    $\left[\nombre{800~000}~\textrm{\euro}~;~\nombre{1~300~000}~\textrm{\euro}\right]$           0,5%
   $\left[\nombre{1~300~000}~\textrm{\euro}~;~\nombre{2~750~000}~\textrm{\euro}\right]$          0,7%
   $\left[\nombre{2~750~000}~\textrm{\euro}~;~\nombre{5~000~000}~\textrm{\euro}\right]$           1%
   $\left[\nombre{5~000~000}~\textrm{\euro}~;~\nombre{10~000~000}~\textrm{\euro}\right]$        1,25%
                               $\geq$ 10 000 000 [€]{.roman}                                     1,5%
:::
