---
title: "Présentation générale"
---

## Architecture des prélèvements obligatoires

*[À rédiger.]*


## Les différentes notions de revenus

> Il existe différentes notions de revenus. Ainsi, lorsqu'un économiste
> parle de revenus, il fait référence aux revenus économiques, aux
> revenus disponibles ou au niveau de vie. Alors que pour le fiscaliste,
> cette notion a une autre définition, elle le ramène aux revenus
> fiscaux. Les nuances importantes dans les mesures de ces différents
> revenus, nous amène à en presenter les définitions afin d'en relever
> les différences:\
>
> -   **Le revenu économique**: Il comprend l'ensemble des revenus
>     supers-bruts reçus par un agent économique pendant une période
>     avant toutes formes de prélèvements.\
>
> -   **Le revenu brut global**: Le revenu brut global est un revenu
>     intermédiaire dans le calcul de l'impôt. Il représente la somme
>     des revenus catégoriels, c'est-à-dire les revenus d'activités
>     (salaires et pensions), les revenus de remplacement (indemnités
>     chômage, pensions alimentaires, pensions d'invalidité et pensions
>     de retraite) et les revenus du patrimoine soumis à l'impôt (les
>     revenus des valeurs et capitaux mobiliers, les revenus fonciers).
>     Tous les montants précédemment cités sont à prendre en compte
>     selon leur définition au sens IRPP [^1] . Ainsi, le revenu brut
>     global est net d'un certain nombre de prélèvements (CSG
>     déductible, cotisations patronales et salariales et taxes sur les
>     salaires) S'ajoute également à ces revenus catégoriels les
>     plus-values réalisées durant l'année.\
>
> -   **Le revenu net imposable (ou revenu global net)**: C'est le
>     revenu brut global réduit de certains déficits observés sur une
>     année (un report des déficits est également possible sous
>     certaines conditions), de certaines charges déductibles (les
>     charges foncières afférentes aux monuments historiques, pensions
>     alimentaires versées, les avantages consentis en nature aux
>     personnes de plus de 75 ans envers lesquels le contribuable n'est
>     soumis à aucune obligation alimentaire, les primes ou cotisations
>     des contrats d'assurance relatifs à l'assurance obligatoire des
>     personnes non salariées contre les accidents de la vie privée, les
>     accidents du travail et les maladies professionnelles dans
>     l'agriculture [^2]), les exonerations prévues par l'article 157 du
>     code général des impôts (CGI), les déductions accordées en
>     fonction du revenu des personnes de plus de 75 ans ou invalides,
>     la déduction des frais professionnels sur les salaires et
>     l'abattement sur les pensions et retraites [^3].\
>     Il est d'usage de prendre en compte le revenu global net du foyer
>     fiscal. Dans ce cas, il se définit comme la somme des revenus nets
>     imposables des individus du foyer fiscal (différent du ménage
>     social [^4]).\
>
> -   **Le revenu fiscal de référence (RFR)**: Il est utilisé comme
>     revenu de référence pour l'attribution de certaines aides et
>     exonérations. Il a l'avantage d'être assis sur une assiette plus
>     large que le revenu net imposable, ce qui lui permet d'être un
>     meilleur indicateur des ressources détenues par un foyer fiscal.
>     Pour le calculer, on ajoute au revenu net imposable le montant des
>     cotisations d'épargne-retraite déduites, de certains revenus
>     exonérés ou soumis aux prélèvements libératoires et de certains
>     abattements [^5].\
>
> -   **Le revenu professionnel** au sens utilisé pour calculer la PPE
>     répond à une définition bien précise. L'activité professionnelle
>     exercée doit pour donner droit à la PPE procurer des revenus au
>     sens IRPP imposables en traitements et salaires ou des revenus
>     imposables dans la catégorie des gérants et associés, des
>     bénéfices professionnels agricoles, des bénéfices industriels et
>     commerciaux ou des bénéfices non commerciaux. Sont par conséquent
>     exclus du champ d'application de la PPE les revenus déclarés en
>     pensions, retraites et rentes, ainsi que dans les catégories des
>     revenus fonciers, des revenus de capitaux mobiliers ou des
>     plus-values. Sont également exclus les prestations sociales ainsi
>     que le RSA.
>
>     Pour assurer une égalité de traitement avec les salariés pour
>     lesquels le calcul de la PPE est assis sur le salaire déclaré
>     avant déduction des frais professionnels (déduction forfaitaire de
>     10% ou frais réels), le total des bénéfices non-salariés déclarés,
>     après application des abattements pour les contribuables relevant
>     du régime micro-entreprise ou du régime déclaratif spécial (cf.
>     ci-dessus) et imputation éventuelle des déficits constatés au
>     titre de l'année résultant d'autres activités non-salariées
>     professionnelles, est majoré de 11,11%.
>
>     Pour les personnes exerçant plusieurs activités (salariées ou non
>     salariées) le revenu à prendre en compte est égal à la somme des
>     différents revenus d'activités professionnelles déclarés,
>     convertis le cas échéant en "équivalent temps plein" sur l'année
>     entière.\
>
> -   **Le revenu disponible**: Il se définit comme le revenu brut
>     global réduit du montant de l'impôt sur le revenu des personnes
>     physiques (IRPP), auquel s'ajoutent la décote, les prestations
>     sociales et la déduction d'impôt due au titre de la prime pour
>     l'emploi (PPE).\

Le tableau [Les différentes définitions des salaires](#micro){reference-type="ref" reference="micro"} détaille
les différents éléments entrant dans la composition du salaire et ceux
qui sont pris en compte lorsqu'on parle de salaire super brut, brut,
imposable à l'IRPP ou de salaire net.

::: {#micro}
  Sont inclus:                                                 super-brut        brut           irpp           net
  ---------------------------------------------------------- -------------- -------------- -------------- --------------
  les taxes sur les salaires                                  $\checkmark$                                
  1-2 les cotisations patronales                              $\checkmark$                                
  1-3 les cotisation salariales                               $\checkmark$   $\checkmark$                 
  1-3 la CSG déductible                                       $\checkmark$   $\checkmark$                 
  1-4 la CSG non déductible et la CRDS                        $\checkmark$   $\checkmark$   $\checkmark$  
  1-5 la part du salaire effectivement reçu par le salarié    $\checkmark$   $\checkmark$   $\checkmark$   $\checkmark$

  : Les différentes définitions des salaires
:::

<!-- AMELIORER CE TABLEAU EN LUI DONNANT UNE ECHELLE ET UN ORDRE DE GRANDEUR. -->
Parmi ces revenus, nous ne ferons référence dans ce guide qu'au revenu
net imposable, qui constitue l'assiette sur laquelle est appliquée le
barème d'imposition par tranches de revenus, et au revenu fiscal de
référence, sur lequel se base l'attribution d'aides et exonérations
telles que la prime pour l'emploi et l'exonération des plus-values
immobilières réalisées par les titulaires de pensions de vieillesse ou
d'une carte d'invalidité.

[^1]: Voir la table 1 page 4 du présent guide pour plus d'explications

[^2]: Cette liste n'est pas exhaustive. Pour plus d'informations se
    référer à l'article 156-II du code général des impôts ou à la
    section Détermination du revenu net global  de ce guide

[^3]: Nous n'avons cité ici que les déductions qui nous ont semblé les
    plus importantes. Pour la liste complètes des déductions permettant
    de calculer le revenu net imposable, se référer aux articles 156 à
    168 du Code général des impôts ou à la section Détermination du
    revenu net global  de ce guide.

[^4]: Le revenu fiscal d'un ménage correspond à l'ensemble des revenus
    déclarés par les foyers fiscaux qui le composent.

[^5]: Pour la liste complète des éléments à ajouter au revenu net
    imposable, se référer à la page X(PPE) du présent guide.
